### ISSUE TITLE
Very basic map in first person mode

### ISSUE THREAD

**Issue by Sebeb** [dhubber/mazed-up#12]
When the player picks up the 3D pill and enters first-person mode, it would be good to have some kind of indication of where they are or which way they're facing, just so it's not too overwhelmingly disorientating. This could either be a compass which points towards the exit, or a basic square which shows the players position relative to the whole maze, without showing any of the maze's walls.

**Comment by dhubber** [comment]
When you say a basic square, do you mean like some small HUD map with a dot for the player, but without an actual map there?  I think that could work definitely, especially if you imagine the player then picks up the 'regenerate map' pill and then has no bloody idea where they are or what the map looks like anymore!

**Comment by Sebeb** [comment]
Yeah, I was thinking just a very minimalistic square with a dot in it, representing where the player is but without any actual walls of the maze being represented. Seems like a good compromise between leaving the player purely to their own devices, and showing an actual map, which I feel would probably undermine the game's mechanics and make the first person pill more of an attribute than a detriment.

Another alternative could be using the normal camera's view as a mini-map and placing it in the top right corner. This would allow the pill to synergize better with all the other pills (rotation would slowly rotate your mini-map, zoom would zoom your minimap, perspective change its perspective etc.) At the moment all these pills are just banned from spawning in the same maze as the first person pill, but of course it would be more elegant if each pill combined with every other combination of pills. I'll play around with this solution.
