### ISSUE TITLE
Level transition issue

### ISSUE THREAD

**Issue by dhubber** [dhubber/mazed-up#37]
On my Mac laptop, when the player enters the lift (love that btw), it goes up but no new level is generated so I can't get to level 2.  Happens either playing in the Editor or by creating a full build!  If it's a Mac-only issue, then I'll have to try and track it down myself.

**Comment by Sebeb** [comment]
You have to press enter to proceed ;) I'm just making the between levels screen, which shows your stats and does have a flashing sign saying press enter/A to proceed, so it should soon hopefully be very clear

**Comment by Sebeb** [comment]
And I'm developing on a mac also actually, so no need to worry about compatibility issues there ;)

**Comment by dhubber** [comment]
Okay, pressing enter just breaks it in a different way for me (both the Editor and the build).  The screen goes blank and there's some different noises and it generates the error : 

MissingReferenceException: The object of type 'Player' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
Game.Update () (at Assets/Resources/Game Objects/Game.cs:220)

Maybe something local you didn't commit/push, or a Prefab update issue?

**Comment by dhubber** [comment]
ok, yes, I forgot actually.  Kind of expecting Macs being the minority in gamedev ;-)

**Comment by Sebeb** [comment]
Ah, that doesn't sound good. Odd, I'm working on the moment and it's playing just fine, although I'm on the b8 branch. I'm pushing my changes to that branch now, maybe try switching to it? If it's still not working, there's a chance it might be a GitHub problem. I know yesterday it was running fine on my mac, then I pushed all my changes, and pulled them on my laptop and a bunch of variables in the inspector were no longer assigned :/ I'll make a current Mac build and put it up on the b8 brunch

**Comment by dhubber** [comment]
ok, seems to be working now thankfuly in the Editor.  I'll just keep this open a little while longer just to be sure but seems fixed now.  (Btw, it's definitely playing nicely :-) .  Found a few small issues that I'll put separately).
