### ISSUE TITLE
Hot walls in the Elevator?

### ISSUE THREAD

**Issue by dhubber** [dhubber/mazed-up#38]
I collected the hot walls pill and then when I entered the elevator to escape, I heard the hot walls sizzling effect on the elevator walls.  I didn't die because the level ended before I lost a life but I guess this could happen in principle.  I guess we don't want this so should be corrected.  If we can confirm this, then I guess it should be fixed!

**Comment by Sebeb** [comment]
Oh yes, that's got to change. From the instant the player is inside the lift it should actually be impossible for them to take damage. But regardless, the hot walls sound and effect shouldn't be triggered by the lift walls
