### ISSUE TITLE
HUD Mini-map strange/different when changing from Isometric -> First person

### ISSUE THREAD

**Issue by dhubber** [dhubber/mazed-up#39]
I was in Isometric mode and then took the First Person pill.  The mini-map seemed to be some strange combination of rotating around some isometric perspective rather than the simple top-down 2d view of the map (which happened the first time I took the first person pill).  Perhaps the mini-map is using the previous camera settings rather than resetting to the top-down?  Will try and confirm next time I play through!

**Comment by dhubber** [comment]
ok, moved mini-map to the bottom right (hopefully correctly!)

**Comment by Sebeb** [comment]
Ah yes, I guess I hadn't tested the first person pill since adding the HUD. It could actually look quite good in the top middle?
So which pill combination exactly are you talking about? The first person pill and the isometric pill combined?
I thought that it would make sense if taking both pills resulted in the player playing first person but with an isometric map

**Comment by dhubber** [comment]
> Ah yes, I guess I hadn't tested the first person pill since adding the HUD. It could actually look quite good in the top middle?
Yes, top middle also could work.  I just put it in the bottom right for now so it's not overlapping the score/time

> So which pill combination exactly are you talking about? The first person pill and the isometric pill combined?
I think it was isometric first and then first person

> I thought that it would make sense if taking both pills resulted in the player playing first person but with an isometric map
Actually I think it looks quite good also.  I just wanted to check it's what you actually intended and not an accidental 'feature' :-)

**Comment by Sebeb** [comment]
I tried it in the middle, and I think it actually looks a lot nicer in the bottom right, far less cluttered.
