### ISSUE TITLE
Player goes invisible sometimes on new level!

### ISSUE THREAD

**Issue by dhubber** [dhubber/mazed-up#41]
For one play-through, once the player character exited the elevator, it went invisible!  I managed to get through a level like this with the player being visible once more in the elevator before becoming invisible again once I entered the next level.  I guess some pill or variable or shader is not being reset correctly and carrying over to the next level.

**Comment by Sebeb** [comment]
Ah yes, this bug suddenly cropped up busy before I built and pushed least night haha. I think their sprite is actually perfectly visible, they've just sunk beneath the floor :stuck_out_tongue_closed_eyes: See need to ensure the player's position is always being reset to the same distance above the maze fit every level

**Comment by dhubber** [comment]
Yes, I was actually guessing the player character is beneath the floor since it's perfectly visible in the lift, just not when it enters the level (maybe the lift isn't going high enough??)

**Comment by Sebeb** [comment]
The lift doesn't actually move when it enters the level, the whole level moves down :stuck_out_tongue_winking_eye: But yeah,  the level probably isn't moving far enough
