### ISSUE TITLE
Game Ending

### ISSUE THREAD

**Issue by Sebeb** [dhubber/mazed-up#7]
At current, the number of levels is determined by the number of pills spawned into the level, meaning the 'penultimate showdown' currently happens at level 18. If we were to add additional pills in the future, or adjust how many pills are spawned per level, this number would change accordingly. We should probably just hard cap the levels to a certain number. I'm thinking either 15, at the current difficulty, or 10 with a severly ramped up difficulty curve.

As to what happens after this, currently the player is taken to a custom built room, every pill, each lying on a pressure plate (although newer pills are not in this room yet.) The idea is that the player is faced with one final, very harsh memory test. Of course anyone getting to the room for a second time will already know that it is worth writing down pill effects, shapes and colours.

 So, should we keep this final test, or just scrap it all together and just cut straight to the win screen, with the player's score? if we decide to keep it, the room will need redoing to include new pills and 3D walls and lighting. I would also add the ability for the player to hear each pill's pickup sound before picking up each pill, which should make remembering each pill's side effect easier. But I'm also open to just scrapping the whole thing.

**Comment by dhubber** [comment]
In my opinion, we should either
1) Scrap the final level, or 
2) If we keep it, we need to inform the player of the pill types they are 'eating'.  One possible suggestion is every time the player eats a pill for the first time, the name/type of pill flashes up on the screen for a few seconds (but only the first time).  Afterwards, the player will have to rely on his/her memory.  Asking a player to find a particular type of pill when they are unsure what that might be called while having to remember them all is asking too much.  And writing them down is just not fun at all!

I would even say flashing up the name/type of pill the first time is a good idea even if we do abolish the final level.  It makes it a bit more interesting than what it is atm.

**Comment by Sebeb** [comment]
I think I'm personally leaning more towards scrapping the final level. I think if we start introducing official names for each pill, which are explicitly stated, the game loses some of its mystery and exploratory nature. I think that once the player realises that each pill has a side effect, figuring out what each side effect does is part of the fun.

**Comment by dhubber** [comment]
I agree that is part of the fun and having names slightly removes that, but it would have definitely been required if we kept the final level as it was because it would have been unfair and frustrating to the player otherwise (it was for me and I had a better idea of what was going on than most!).  But if we scrap it, then there's no need for names at all.

**Comment by Sebeb** [comment]
Alright, so are you're okay just deciding to scrap the showdown level then?

**Comment by dhubber** [comment]
Yes, let's scrap it!

**Comment by Sebeb** [comment]
Cool, so I'll change the new final level (previously the penultimate trial), always arrives at a specific level, rather than being reliant on all pills having been spawned in the previous level. I'll set the number to 10 for the time being, but we can always change that number around. Would be good to maybe get some playtesting feedback as to what kind of length is best.
